### ISSUE TITLE
Auszug/Einzug von Agenten

### ISSUE THREAD

**Issue by Lwinkeler** [quarree100/q100_abm#13]
- [x] Eigenschaft Auszugswahrscheinlichkeit anlegen
 - Variable Altersgruppe hinzufügen
 - csv-Liste mit Wohndauer (mit/ohne geburtsort) importieren &  anwenden
 - Agenten nach Wahrscheinlichkeit "ausziehen" lassen (`do die;`)
- [x] Wenn Wohneinheit frei -> Erstellung neuer *Haushalte* an dieser Stelle
 - Einordnung in die Altersgruppe 21-40
 - Einkommensklasse entsprechen der Ursprungsverteilung gewichtet verteilen
 - Berufsgruppe zufällig verteilen mit Ausnahme "pensioniert"
 - Netzwerkvariablen ergeben sich hieraus
 - Evtl zufällige Auswahl des Quartils
_____________

- [x] s.u. Wechsel employment-status

**Comment by Lwinkeler** [comment]
Bisher beinhaltet die csv-Datei keine Wahrscheinlichkeit, sondern Wohndauer.

- Erstellen einer Auszugswahrscheinlichkeit aus der Wohndauer
- 1/Wohndauer

**Wichtig:** Es sollte gewährleistet sein, dass sich die Wahrscheinlichkeit mit einem Wechsel von Altersgruppe 20-40 zu 40-60 ebenfalls je Haushalt ändert.

**Comment by Lwinkeler** [comment]
Edit:
`	int lenght_of_residence <- 0; //years since the household moved in 
`
**TODO: ggf noch anders verteilen, damit nicht alle bei 0 starten**

**Comment by phiola** [comment]
> `int lenght_of_residence <- 0; //years since the household moved in `
> **TODO: ggf noch anders verteilen, damit nicht alle bei 0 starten**

Die Variable hat bis jetzt noch keine Funktion, deshalb hab ich jetzt noch nichts geändert.

**Comment by Lwinkeler** [comment]
todo:
- Ergänzung Wechsel employment-Status ab Alter 64 [statista-quelle](https://de.statista.com/statistik/daten/studie/616566/umfrage/entwicklung-des-renteneintrittsalters-in-deutschland/)
- bei Bedarf Wahrscheinlichkeit einführen, bspw. ab Alter 60 mit 50%iger Wahrscheinlichkeit Wechsel employment -> pensioner

**Comment by phiola** [comment]
Ist hinzugefügt. (commit b05ce9d)
